# Generated by Django 3.1.7 on 2021-02-25 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QueryMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('src', models.CharField(max_length=500, unique=True)),
                ('dist', models.CharField(max_length=500, unique=True)),
                ('path', models.CharField(max_length=500, unique=True)),
                ('lenPath', models.FloatField(unique=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
